#!/usr/bin/env ruby
# frozen_string_literal: true

require "xcodeproj"
require "fileutils"

ROOT_DIR = File.expand_path("../..", __dir__)
DEFAULT_XCODEPROJ = File.join(ROOT_DIR, "ios", "JunoNativeApp.xcodeproj")

xcodeproj_path = ENV["XCODEPROJ_PATH"].to_s.strip
xcodeproj_path = DEFAULT_XCODEPROJ if xcodeproj_path.empty?

app_identifier = ENV["APP_IDENTIFIER"].to_s.strip
team_id        = ENV["APPLE_TEAM_ID"].to_s.strip

unless File.exist?(File.join(xcodeproj_path, "project.pbxproj"))
  abort <<~MSG
    ❌ Xcode project not found at: #{xcodeproj_path}

    This CI pipeline expects an application project generated by XcodeGen from:
      ios/JunoNativeApp.yml  ->  ios/JunoNativeApp.xcodeproj

    Fix:
      1) Ensure XcodeGen is installed on the runner:  brew install xcodegen
      2) Run: ruby scripts/ci/generate_ios_project.rb
  MSG
end

project = Xcodeproj::Project.open(xcodeproj_path)

def app_target?(t)
  return true if t.respond_to?(:product_type) && t.product_type.to_s.start_with?("com.apple.product-type.application")
  begin
    cfg = t.build_configurations.first
    ext = cfg.build_settings["WRAPPER_EXTENSION"].to_s
    return true if ext == "app"
  rescue StandardError
    # ignore
  end
  false
end

app_targets = project.targets.select { |t| t.is_a?(Xcodeproj::Project::Object::PBXNativeTarget) && app_target?(t) }

if app_targets.empty?
  names = project.targets.map(&:name).join(", ")
  abort <<~MSG
    ❌ No iOS application targets found in #{xcodeproj_path}.
    Targets seen: #{names}

    If you only see a static library target (common in this repo),
    you MUST generate the app project via XcodeGen first:
      ruby scripts/ci/generate_ios_project.rb
  MSG
end

app_targets.each do |t|
  t.build_configurations.each do |cfg|
    bs = cfg.build_settings

    # Root fix: ensure the app is installed into the archive.
    bs["SKIP_INSTALL"] = "NO"
    bs["INSTALL_PATH"] = "$(LOCAL_APPS_DIR)" if bs["INSTALL_PATH"].to_s.empty?

    # Deterministic CI defaults.
    bs["DEBUG_INFORMATION_FORMAT"] = "dwarf-with-dsym" if cfg.name.to_s.downcase == "release"
    bs["SUPPORTED_PLATFORMS"] = "iphoneos iphonesimulator" if bs["SUPPORTED_PLATFORMS"].to_s.empty?
    bs["TARGETED_DEVICE_FAMILY"] = "1,2" if bs["TARGETED_DEVICE_FAMILY"].to_s.empty?
    bs["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0" if bs["IPHONEOS_DEPLOYMENT_TARGET"].to_s.empty?

    # Make the generated XcodeGen placeholder values safe for real CI signing.
    bs["PRODUCT_BUNDLE_IDENTIFIER"] = app_identifier unless app_identifier.empty?
    bs["DEVELOPMENT_TEAM"] = team_id unless team_id.empty?

    # Xcode 14+ ignores bitcode, but leaving it explicitly off avoids warnings.
    bs["ENABLE_BITCODE"] = "NO" if bs.key?("ENABLE_BITCODE")
  end
end

project.save

puts "✅ Patched #{xcodeproj_path}"
puts "   - App targets: #{app_targets.map(&:name).join(', ')}"
puts "   - SKIP_INSTALL=NO, INSTALL_PATH=$(LOCAL_APPS_DIR)"
puts "   - Bundle id set to #{app_identifier}" unless app_identifier.empty?
puts "   - Team id set to #{team_id}" unless team_id.empty?
